export const USER_STATE_CHANGE = "USER_STATE_CHANGE";
export const CLEAR_DATA = "CLEAR_DATA";
export const GET_ALL_VOZIKY = "GET_ALL_VOZIKY";
export const GET_USER_VOZIKY = "GET_USER_VOZIKY";
export const GET_ALL_USERS = "GET_ALL_USERS";
